port = "9999"
authUsername = "username"

# Use http://www.htaccesstools.com/htpasswd-generator/ to generate a hash from your plaintext password
authPassword = "password"

[[db]]
label = "local-1"
database = "test1"
connectionString = "mongodb://localhost"

[[db]]
label = "local-2"
database = "test2"
connectionString = "mongodb://localhost"