port = "9999"
authUsername = "username"

# Use http://www.htaccesstools.com/htpasswd-generator/ to generate a hash from your plaintext password
authPassword = "password"

[[db]]
label = "Main"
database = "main"
connectionString = "mongodb://localhost"

[[db]]
label = "Reports"
database = "reports"
connectionString = "mongodb://localhost"