port = "9999"
authUsername = "james"

# Use http://www.htaccesstools.com/htpasswd-generator/ to generate a hash from your plaintext password
authPassword = "james"

[[db]]
label = "local-1"
database = "maxwellv5"
connectionString = "mongodb://localhost"

[[db]]
label = "local-2"
database = "test2"
connectionString = "mongodb://localhost"